### PR TITLE
Fixes #941 Remove unused step in plan select modal

### LINKED ISSUE #941: Choose plan button shall redirect to checkout
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 2.2.3.2 and 2.2.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When clicking choose plan , we are redirected to another modal to select plan instead of checkout

**To Reproduce**
1. starter account , quota > 20%
2. install and activate imagify
3. Click upgrade now in settings page
4. click choose plan button => this modal is displayed instead of checkout
Image

**Expected behavior**
When click choose plan, redirect to checkout modal

**Additional context**
- it started on 2.2.3

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming
1. We need to remove the banner from the screenshot
2. We need to make sure that the query that calculates the number of images related to this banner is not run
3. We need to make sure that the existing banner redirects correctly to the checkout (both plans, monthly and yearly)

### PR DESCRIPTION
**Pull request by remyperona**
# Description

Fixes #941

Remove unused step in plan select modal, to go directly from plan select to the checkout page

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## Detailed scenario

- Display the upgrade plan modal
- Select a plan
- next page is the checkout page

### Documentation

Removed a lot of unused code, related to the old step + one time plans. Also removed unnecessary request to get the number of images optimized and related data.

Update the JS code to go to the appropriate checkout page depending on the plan and period selected.

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.

## Unticked items justification

No code coverage possible for the code changed in this PR

### CODE REVIEW

**Review by jeawhanlee — APPROVED** [review]

**Comment by jeawhanlee** [comment]
Tested that this works as expected.

**Comment by wordpressfan** [comment]
@remyperona Many thanks Boss.

@jeawhanlee can u plz resolve conflicts and then move this to `Ready for QA`?
Thanks

**Comment by jeawhanlee** [comment]
Yes on it

**Comment by Mai-Saad** [comment]
@remyperona @jeawhanlee Thanks for the PR.  Please note that clicking Choose plan is doing nothing now. can you please check :pray:  => **seems working fine after hard refresh**

**Review by Mai-Saad — APPROVED** [review]
[testrail-report-671.pdf](https://github.com/user-attachments/files/18197805/testrail-report-671.pdf)

**Pull request merged**
