### PR TITLE
Closes #727 Update admin bar upsell

### LINKED ISSUE #727: Update the account status notification in the toolbar menu
We would like to update copy and color for the part of the account status notification in the toolbar menu (red box), for the users who are <= 20% of the unconsumed quota.

Details are provided [here](https://docs.google.com/document/d/18dnmVYjUaNk5T1cGDcozPrSPg6UeqhcqnhaR_sUj1tQ/edit#).

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Update the admin bar upsell block when under 20% of quota

Fixes #727

## Type of change

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [x] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [x] I validated all test plan the QA Review asked me to.

### CODE REVIEW

**Review by mostafa-hisham — APPROVED** [review]

**Comment by vmanthos** [comment]
@Tabrisrp Can you please take care of the conflicts when you have some time? :pray: 
These came after merging https://github.com/wp-media/imagify-plugin/pull/752.

Also, the `$is_monthly` isn't set in:
https://github.com/wp-media/imagify-plugin/blob/7b51656d42f35dbdbb8b1a8bf2267508cfafc205/classes/User/User.php

and this results in displaying the yearly offer regardless of what the user is using.

**Comment by remyperona** [comment]
@vmanthos It's updated

**Comment by vmanthos** [comment]
@Tabrisrp Thank you for the PR.

I can see the toolbar upsell box even when the available quota is `>20%`:
image

Also, for the Infinite plan, the following is displayed:
image

These :point_up: are from a real user, i.e. I haven't mocked the response.

Can you please look into this? :pray:

**Comment by remyperona** [comment]
You're right I forgot one condition in the view, it should be good now

**Review by vmanthos — APPROVED** [review]
Thank you for the fixes, @Tabrisrp!

This is working as expected. :+1: 

**TestRail report:** Will be added when ready.

**Pull request merged**
