### PR TITLE
Fixes #833 Delete all next-gen versions on restore original image

### LINKED ISSUE #833: Restore original image shall delete all existing next-gen independent on what's enabled
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => commit 6a7f2f324a0f2fccdc35f046629da372f990e9ec
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When click restore original image, we delete only next-gen that is currently enabled instead of deleting all as same as on trunk or while delete next-gen

**To Reproduce**
1. install/activate imagify
2. upload image => webp is created
3. enable avif => avif created (if not created , click generate next-gen link)
4. click restore image in media library => only avif is deleted

**Expected behavior**
both webp and avif shall be deleted

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

### PR DESCRIPTION
**Pull request by remyperona**
# Description

Correctly delete all next-gen versions on restore original image by passing the second parameter of the methods to true

Fixes #833

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I did not introduce unecessary complexity.

### CODE REVIEW

**Review by Miraeld — APPROVED** [review]

**Comment by Mai-Saad** [comment]
related test plan https://wpmediaqa.testrail.io/index.php?/runs/view/825&group_by=cases:section_id&group_order=asc

**Comment by jeawhanlee** [comment]
Testing in progress...

**Comment by jeawhanlee** [comment]
Thank you for the PR @Tabrisrp.
During execution of test plan, with webp versions available and avif enabled, when` reoptimize with lossless compression` is clicked the webp versions are deleted and avif created, While on trunk webp versions is untouched, Do we need to fix this @piotrbak ?

**Comment by piotrbak** [comment]
Yes, that sounds like a regression. @Tabrisrp the lossless/smart compression is related to the image optimization only, not the generation of webp/avif, right?

**Comment by remyperona** [comment]
The lossless level also applies to the next-gen versions, so it makes sense to delete and re-create them too

**Comment by piotrbak** [comment]
@Tabrisrp Looks like @Mai-Saad and @jeawhanlee were correct here. Currently in 2.2 we're not touching the version that's not enabled. 

Is this a big effort to redo this change?

**Comment by remyperona** [comment]
It would mean to go back to the previous state, so the issue this PR is fixing would not be fixed.

Re-optimizing process is first restore the original, then optimize again with new settings, so it uses the same underlying restore methods.

**Comment by MathieuLamiot** [comment]
@piotrbak how can we align on the expected behavior to move forward? Should we set up a quick call this afternoon or not needed?

**Comment by piotrbak** [comment]
@MathieuLamiot I think we're okay with what @Tabrisrp explained.

@Mai-Saad We'll need to update the TCs

**Review by Mai-Saad — APPROVED** [review]
[testrail-report-585.pdf](https://github.com/wp-media/imagify-plugin/files/14613248/testrail-report-585.pdf)

**Pull request merged**
