### PR TITLE
Fixes #542 CSS conflict with Imagify

### LINKED ISSUE #542: CSS conflict with Imagify
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Imagify is present, there's a CSS conflict with the `Clear Cache` button in the dashboard.

**To Reproduce**
1. Enable WP Rocket
2. Enable Imagify
3. Go to the Imagify dashboard

**Expected behavior**
WP Rocket's button shouldn't be styled in Imagify way

**Screenshots**
image

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by mostafa-hisham**
issue #542 
fix css form button and run grunt css

### CODE REVIEW

**Review by iCaspar — APPROVED** [review]

**Comment by iCaspar** [comment]
Ready for @wp-media/qa

**Comment by piotrbak** [comment]
@mostafa-hisham This banner is still in Imagify style:
image
image

To reproduce:
1. Install newest `WP Rocket`
2. Install `Imagify`
3. Install `WP Downgrade | Specific Core Version`
4. Go to the `Settings > WP Downgrade` and set it to 5.2
5. Go to the `Dashboard > Updates` and install 5.2 version
6. Go to the Imagify settings section

**Review by piotrbak — CHANGES_REQUESTED** [review]
We need to take care of all WP Rocket banners

**Review by piotrbak — APPROVED** [review]
Ready to go!

**Pull request merged**
