### PR TITLE
Fix NGINX Rewrite Rules

### PR DESCRIPTION
**Pull request by markonikolic985**
As we have confirmation from one user that removing "final" worked for them, sending this Pull request.

Issue: https://github.com/wp-media/imagify-plugin/issues/423

Ticket: https://secure.helpscout.net/conversation/1138088855/158359?folderId=676702

### CODE REVIEW

**Comment by AnthoRdev** [comment]
What's happened with this issue? Is that the correct way to solve the problem, removing the "final" parameter?

**Comment by GeekPress** [comment]
@markonikolic985 Can you please explain to @Davidacu how to reproduce the issue, and how to check it's fixed with the new code?

**Comment by markonikolic985** [comment]
@Davidacu 

**How to reproduce the issue**

You need NGINX server with SSH access.

- If possible, connect via SSH and keep the terminal opened

- Activate "Display WebP" using rewrite rules on NGINX server

-  You should already have error, if not - check nginx.config (NGINX configuration file) with `nginx -t`

The error should look like:

`invalid parameter "final" in /nginx_rules_custom.conf:15`

**How to fix the issue**

- Remove `final` from this line: `rewrite ^(.*) $1.webp final;`

- Restart NGINX `systemctl reload nginx`

- Check the syntax again with `nginx -t`

It should be working fine.

**Comment by iCaspar** [comment]
@wp-media/qa Ready for QA.

**Review by Davidacu — APPROVED** [review]
- I was able to reproduce the error in 1.9.10
- I can confirm that the `/conf/imagify.conf` file generated does not have **final**
- I can confirm that webp images are served when "rewrite rules" are set
tested in https://spinupwp.wp-rocket.me/sample-page/

**Comment by hellofromtonya** [comment]
@Davidacu Is QA done on this one? If yes, please approve the PR.

**Pull request merged**
