### PR TITLE
Fixes #566 Improve display of settings and bulk pages on mobile

### LINKED ISSUE #566: Issue with the Imagify Settings page on a mobile device
The Imagify Settings page on a mobile device does not look good. A user mentioned it [here](https://wordpress.org/support/topic/suggestions-and-some-questions/)
Imagify settings

### PR DESCRIPTION
**Pull request by mostafa-hisham**
issue #566
fix mobile css for setting and bulk pages

### CODE REVIEW

**Review by iCaspar — CHANGES_REQUESTED** [review]
CSS Changes look great!
Phpcs needs some spacing adjustments in `views/part-settings-custom-folders.php`
but should be easy to see now that the 7.4 updates are merged!

**Comment by remyperona** [comment]
Since we're on the subject of CSS, can we check if what is reported in https://github.com/wp-media/imagify-plugin/issues/174 is also fixed by this PR?

**Comment by mostafa-hisham** [comment]
@Tabrisrp 
I did some changes to fix the big promotion banner on mobile in #174 

the desktop issue I think it is fixed I don't see any overlap
image

**Review by iCaspar — APPROVED** [review]

**Comment by iCaspar** [comment]
Ready for @wp-media/qa

**Comment by piotrbak** [comment]
@Tabrisrp @mostafa-hisham I think this button should be below the text and might be bigger. However, I'm not a design person :/ 
image

Also, the checkout modal is not usable at all on both, trunk and branch:
image

**Comment by piotrbak** [comment]
@mostafa-hisham Would be good to have a small margin top or padding here, above the `Need help(...)`:
image

Also, the checkout process is not responsive after choosing the plan and moving forward. I think it comes from the Imagify app, right?

**Comment by mostafa-hisham** [comment]
@piotrbak 
> @mostafa-hisham Would be good to have a small margin top or padding here, above the `Need help(...)`:
> image
> 
**FIXED**
> Also, the checkout process is not responsive after choosing the plan and moving forward. I think it comes from the Imagify app, right?
>
**Yes**

**Review by piotrbak — APPROVED** [review]

**Pull request merged**
