### PR TITLE
Add filter for nextgen image format #777

### LINKED ISSUE #777: AVIF support: filters to manage images formats to generate
### Scope a solution ✅ 
- Add a new filter `imagify_nextgen_images_formats`, with an array containing the next-gen images formats to generate
- Use this filter in a method to get the image formats to generate, that can be re-used where necessary
- This method will by default use the WebP value, replaced by AVIF if enabled in the UI
- Modifying the filter value will allow to either generate both formats, or none of them

### Estimate the effort ✅
Effort [S]

### PR DESCRIPTION
**Pull request by Khadreal**
## Description

Add `imagify_nextgen_images_formats` filter

Fixes #777

## Type of change
- New feature (non-breaking change which adds functionality).

## Is the solution different from the one proposed during the grooming?
No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

### CODE REVIEW

**Comment by jeawhanlee** [comment]
@Tabrisrp This PR is dependent on this: https://github.com/wp-media/imagify-plugin/pull/782 no?

**Comment by Khadreal** [comment]
> @Tabrisrp This PR is dependent on this: #782 no?

To the best of my knowledge, no

**Review by remyperona — CHANGES_REQUESTED** [review]
This is how I was picturing it so that we can re-use the function whenever we need:

```
function imagify_nextgen_images_formats() {
    $formats = [
        'webp',
    ];

    if ( get_imagify_option( 'convert_to_avif' ) ) {
        $formats[] = 'avif';
    }

    $default = $formats;
    /**
     * Filters the array of next gen formats to generate with Imagify
     *
     * @since 2.2
     *
     * @param array $formats Array of image formats
     */
    $formats = apply_filters( 'imagify_nextgen_images_formats', $formats );

    if ( ! is_array( $formats ) ) {
        $formats = $default;
    }

    return $formats;
}
```

**Comment by Khadreal** [comment]
> This is how I was picturing it so that we can re-use the function whenever we need:
> 
> ```
> function imagify_nextgen_images_formats() {
>     $formats = [
>         'webp',
>     ];
> 
>     if ( get_imagify_option( 'convert_to_avif' ) ) {
>         $formats[] = 'avif';
>     }
> 
>     $default = $formats;
>     /**
>      * Filters the array of next gen formats to generate with Imagify
>      *
>      * @since 2.2
>      *
>      * @param array $formats Array of image formats
>      */
>     $formats = apply_filters( 'imagify_nextgen_images_formats', $formats );
> 
>     if ( ! is_array( $formats ) ) {
>         $formats = $default;
>     }
> 
>     return $formats;
> }
> ```

Cool! I was thinking we would use filter in place of calling the function.

**Review by Miraeld — APPROVED** [review]

**Review by remyperona — APPROVED** [review]

**Pull request merged**
