### PR TITLE
Fixes #721 Prevent PHP errors

### LINKED ISSUE #721: FILTER_SANITIZE_STRING deprecation notice with PHP 8.1
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: 
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

```PHP
PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /var/www/example.com/htdocs/wp-content/plugins/imagify/inc/classes/class-imagify-views.php on line 511
```

**To Reproduce**

1. Use PHP 8.1.
2. Activate Imagify.
3. Visit the media library page: `/wp-admin/upload.php`
4. See the notice in the `debug.log`.

**Expected behavior**

No deprecation notices should be there when using Imagify with PHP 8.1.

**Additional context**

`FILTER_SANITIZE_STRING` is used in [other places](https://github.com/search?q=repo%3Awp-media%2Fimagify-plugin%20FILTER_SANITIZE_STRING&type=code) in Imagify's code. Those should be tackled as well.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by remyperona**
Check if array keys exists before using them

Fixes #721

### CODE REVIEW

**Review by engahmeds3ed — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@Tabrisrp Thanks for the PR. Can you please check the following cases :pray: 
Can reproduce the following error using PHP 8.2 and the PR
```
[12-Jul-2023 10:41:48 UTC] PHP Warning:  Undefined array key "option_page" in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/imagify/inc/classes/class-imagify-settings.php on line 134
[12-Jul-2023 10:41:48 UTC] PHP Deprecated:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/imagify/inc/classes/class-imagify-settings.php on line 134
```
Scenario1:
steps:
1- use a wrong API key
2- correct the API key and save

Scenario2: => even without step 1 , we have the same error on newlabs
1- delete AS actions table
2- fresh install and activate of the PR

**Comment by remyperona** [comment]
Thanks, I updated the code to prevent it too

**Comment by piotrbak** [comment]
@engahmeds3ed Could you do a CR after last changes here?

**Review by mostafa-hisham — APPROVED** [review]

**Review by mostafa-hisham — APPROVED** [review]

**Comment by mostafa-hisham** [comment]
@piotrbak i didn't get the warning in the issue but got this one
```
[30-Aug-2023 04:53:45 UTC] PHP Deprecated:  Return type of Imagify_Files_Iterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/mostafa/Local Sites/wp-copra/app/public/wp-content/plugins/imagify-plugin/inc/classes/class-imagify-files-iterator.php on line 65

[30-Aug-2023 05:29:07 UTC] PHP Deprecated:  Return type of Imagify_Files_Recursive_Iterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/mostafa/Local Sites/wp-copra/app/public/wp-content/plugins/imagify-plugin/inc/classes/class-imagify-files-recursive-iterator.php on line 55
```
**Steps:**
php v8.1
1- add `wp-content/themes/twentytwentytwo/` folder in imagify settings (this triggers the first warning)
2- click bulk optimization  (this triggers a second warning after the first step)

**FYI**: adding `#[\ReturnTypeWillChange]` fix the problem but i am not sure if it is the best way to handle it.

and when i did the second testing scenario [here](https://github.com/wp-media/imagify-plugin/pull/735#issuecomment-1632554713) i got alot of fatal error but i don't think it is related to this PR.
I think it should be covered [here](https://github.com/wp-media/imagify-plugin/issues/720)

**Pull request merged**
