### PR TITLE
Closes #888 Fatal error when having image size with integer name

### LINKED ISSUE #888: Fatal error when having image size with integer name
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**

In a customer's site we face the following error:
```
[23-May-2024 08:15:14 UTC] PHP Fatal error:  Uncaught TypeError: strpos() expects parameter 1 to be string, int given in /home/customer/www/staging2.xxx.com/public_html/wp-content/plugins/imagify/classes/Optimization/Process/AbstractProcess.php:1641
Stack trace:
#0 /home/customer/www/staging2.xxx.com/public_html/wp-content/plugins/imagify/classes/Optimization/Process/AbstractProcess.php(1641): strpos(200, '@imagify-webp')
#1 [internal function]: Imagify\Optimization\Process\AbstractProcess->Imagify\Optimization\Process\{closure}(200)
#2 /home/customer/www/staging2.xxx.com/public_html/wp-content/plugins/imagify/classes/Optimization/Process/AbstractProcess.php(1642): array_filter(Array, Object(Closure))
#3 /home/customer/www/staging2.xxx.com/public_html/wp-content/plugins/imagify/inc/functions/admin-ui.php(100): Imagify\Optimization\Process\AbstractProcess->is_full_next_gen()
#4 /home/customer/www/staging2.xxx.com/public_html/wp-content/plugins/imagify/inc/functions/admin-ui.php(529): g in /home/customer/www/staging2.xxx.com/public_html/wp-content/plugins/imagify/classes/Optimization/Process/AbstractProcess.php on line 1641
```

and this happens exactly here:

https://github.com/wp-media/imagify-plugin/blob/a5b782019155e99326c7fddf1b031750b0c50c82/classes/Optimization/Process/AbstractProcess.php#L1641

In the PR (#877) we fixed similar issue when the image size name is not integer, but we once the image is optimized we save the sizes in the attachment metas to be grabbed later on the mentioned line (as far as I understand) but in php if the array has numeric keys even if u added them as strings, this will be cast to be integer then it throws the previously mentioned fatal error.

**To Reproduce**
1. Add the following snippet
```
add_action( 'after_setup_theme', function() {
    add_image_size( '200', 200, 200 );
} );
```
2. Optimize any image and wait till it's optimized for this new size.
3. Open any post and choose the featured image
4. once media modal is opened, fatal error should be thrown and images not loaded in the modal.

**Expected behavior**
Images should load without a problem.

I fixed this by casting the $key variable here:

https://github.com/wp-media/imagify-plugin/blob/a5b782019155e99326c7fddf1b031750b0c50c82/classes/Optimization/Process/AbstractProcess.php#L1641

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

### PR DESCRIPTION
**Pull request by Khadreal**
# Description

Fixes #888 

### User documentation
Should work as expected without any impact

### Technical documentation
Type cast integer image size name to string

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation
- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I did not introduce unecessary complexity.

### CODE REVIEW

**Review by wordpressfan — APPROVED** [review]
Awesome job

**Review by Mai-Saad — COMMENTED** [review]
Reproducible steps:
1- Add snippet in the functions.php of active theme
2- fresh install /activate of imagify
3- Upload large image
4- click optimize 1 missing thumbnail link
marchlarge1

**Comment by wordpressfan** [comment]
@Khadreal @Mai-Saad @piotrbak  I believe we need to merge this one, correct?

**Comment by piotrbak** [comment]
@wordpressfan Yes

**Pull request merged**
