### PR TITLE
Fixes #788 Generate next-gen formats on image upload

### LINKED ISSUE #788: V2.2: WebP image isnot automatically generated with upload
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => Avif commit: b396de27
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WebP is not automatically generated after uploading an image

**To Reproduce**
1. Fresh activation of Imagify (Auto-Optimize images on upload is enabled, optimization is not enabled)
2. Add valid key
3. Upload image
4. Check media library

**Expected behavior**
WebP is generated by default as AVIF is not checked

**Screenshots**
Screenshot from 2024-02-02 08-16-14

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

### PR DESCRIPTION
**Pull request by remyperona**
# Description

This PR updates the AbstractProcess class to correctly generate the appropriate next-gen formats on image upload.

Fixes #788

### Technical documentation

We use `imagify_nextgen_images_formats()` to determine which next-gen formats are currently enabled, and add the corresponding conversions to the array of images to send to the API.

It also fixes the comparison between the non-next-gen size vs next-gen size, to determine if we should keep the next-gen or not, and some of the code evaluating if the current size is next-gen or not.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I did not introduce unecessary complexity.

### CODE REVIEW

**Review by Miraeld — APPROVED** [review]
I've tried it in local and it works as expected :)

**Comment by Mai-Saad** [comment]
@Tabrisrp Thanks for the PR. currently, webP images are generated with upload but it's consuming quota. can you please check? Do we need other GH to stop consuming quota for webP?

**Comment by remyperona** [comment]
The quota consumption is handled on the API side, I believe it has not yet been updated there. It won't require any plugin change.

**Comment by johngathure** [comment]
> @Tabrisrp Thanks for the PR. currently, webP images are generated with upload but it's consuming quota. can you please check? Do we need other GH to stop consuming quota for webP?

Hello Mai, this has already been fixed (on the API side), but has not been released yet, @piotrbak recommended it to be released with 2.2.

**Pull request merged**
