### PR TITLE
Fixes #789 Fix error displayed when using generate missing next-gen versions button

### LINKED ISSUE #789: Error is displayed when click 'Generate Missing Next-Gen Images Versions' while no optimization is selected
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => Avif commit: https://github.com/wp-media/imagify-plugin/commit/b396de27cda71d9b16e311a0f55f482bebf13380
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Error is displayed when clicking 'Generate Missing Next-Gen Images Versions'

**To Reproduce**
1. Fresh activation of Imagify
2. Click on 'Generate Missing Next-Gen Images Versions'

**Expected behavior**
WebP versions are generated while AVIF is not checked

**Screenshots**
Screenshot from 2024-02-02 08-22-27

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming
- If AVIF is checked and we detect that there are missing AVIF images for optimized ones, we’ll create only AVIF versions for the images
- If AVIF is not checked, we’ll create only Webp versions for the images
- If filter is set to generate both AVIF/WebP, then both will be generated while AVIF option is checked
- WebP generation won't consume quota

### PR DESCRIPTION
**Pull request by remyperona**
# Description

Remove avif as a supported mime type to prevent the error reported, as the format is not currently supported by the Imagick/GD implementation in WP (coming in 6.5).

Also update the ajax URL identifier for the generate missing next-gen versions in the JS file.

Fixes #789

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I named variables and functions explicitely.
- [x] I did not introduce unecessary complexity.

## Observability
- [x] I handled errors when needed.

### CODE REVIEW

**Comment by Miraeld** [comment]
Shouldn't this [file](https://github.com/wp-media/imagify-plugin/blob/a115859a49edc93d4f598034eaf04ebd5dfdbe57/assets/js/options.min.js) be modified/updated as well ?

**Comment by jeawhanlee** [comment]
@Tabrisrp I did a small manual test with the PR branch and I got this error when I click on `Generate missing next-gen images version`:

Screenshot 2024-02-19 at 13 10 09

**Comment by remyperona** [comment]
I can't replicate it, did you have AVIF conversion enabled or not?

**Comment by jeawhanlee** [comment]
> I can't replicate it, did you have AVIF conversion enabled or not?

Avif was disabled when I checked this but with Avif enabled, I still get the error.

**Comment by piotrbak** [comment]
@jeawhanlee What kind of environment did you use? Was it a local or live one?

**Comment by jeawhanlee** [comment]
@piotrbak A local

**Comment by piotrbak** [comment]
@Tabrisrp Are we okay with this comment made by @Miraeld?
https://github.com/wp-media/imagify-plugin/pull/805#issuecomment-1952300279
If that's okay, let's move forward with CR. 

@jeawhanlee let's see if QA will be able to reproduce this problem, if it's there we should also check if it's a regression when comparing to the current trunk version.

**Comment by remyperona** [comment]
Yes it's fine we can update the minified files at the end

**Comment by Mai-Saad** [comment]
@Tabrisrp Thanks for the PR. Got the same error mentioned by @jeawhanlee on both local and https://imagify.rocketlabsqa.ovh/ while AVIF is enabled or disabled. can you please check :pray:  (working fine on trunk)
Screenshot from 2024-02-22 14-41-00

**Comment by remyperona** [comment]
It might be related to the fixes done in https://github.com/wp-media/imagify-plugin/pull/806

**Pull request merged**
