### PR TITLE
Closes #2884 Upgrade plan link in admin bar

### PR DESCRIPTION
**Pull request by remyperona**
# Description

Fixes #2884

Add an upgrade plan link in the admin bar for free users with quota < 20%

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).

## Detailed scenario

- Free account with more than 20% quota remaining
- Display the imagify admin bar sub-menu
- Upgrade plan link is displayed
- Clicking on link opens the subscription popup

upgrade-plan

### Documentation

Display the button if free user and quota > 20%

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.

### CODE REVIEW

**Review by Khadreal — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@Tabrisrp Thanks for the PR.
- currently, the upgrade plan link is displayed when the remaining quota for the starter (free) user is <= 20% ==> It shall be displayed when the free account has a remaining quota > 20%. Can you please check? :pray: (confirmed with @marija-nikolic )
starter 20remaining

- if we click the upgrade link, we will have an empty loading popup. can you please check :pray: or let us know if anything needs to be done so popup data is displayed
emptyPopUp

**Comment by marija-nikolic** [comment]
I've noticed there is a mistake here. If we have a pink banner displayed, we don't need a green "Upgrade plan" button.
You have details on this [Notion page](https://www.notion.so/wpmedia/Upsell-initiatives-plugin-909fc8bddd1f480ebd566317d49e8d16)

image

I've just discussed it with Mai.

**Review by Miraeld — APPROVED** [review]

**Comment by marija-nikolic** [comment]
@Tabrisrp @Mai-Saad Did we fix this issue here with having both upgrade options (green and pink)?

**Comment by Mai-Saad** [comment]
> @Tabrisrp @Mai-Saad Did we fix this issue here with having both upgrade options (green and pink)?

Yes can see it fixed now
Screenshot from 2024-10-07 13-38-57

- upgrade link
Screenshot from 2024-10-08 09-28-24

- popup after clicking link still keeps loading with me, @Tabrisrp can you please add screenshot of popup
Screenshot from 2024-10-08 09-27-51

**Review by wordpressfan — CHANGES_REQUESTED** [review]
Do we need to build the minified assets here?
We tried this PR in our test site and when `SCRIPT_DEBUG` equals `false` we see:

Screenshot from 2024-10-08 10-37-23

and once we set it to true, we see:

Screenshot from 2024-10-08 10-37-45

That's why I think we need to build assets.

**Comment by remyperona** [comment]
Updated the JS min file that was missing

**Comment by Mai-Saad** [comment]
- upgrade style is good now while script_debug is false
Screenshot from 2024-10-10 15-46-02
Screenshot from 2024-10-10 15-45-46

Screenshot from 2024-10-10 15-46-25
- The banner is displayed when click upgrade (the new banner is in another PR as per @Tabrisrp )
Screenshot from 2024-10-10 15-48-40

**Pull request merged**
