### PR TITLE
Closes #763: AVIF support: UI

### LINKED ISSUE #763: AVIF support: UI
### Scope a solution ✅ 
In `views/part-settings-webp.php`:
- Update button label from `generate missing webp versions` to `generate missing next-gen images versions`

In `views/button/generate-webp.php`:
- Update button label from `generate webp versions` to `generate next-gen images versions`

In `views/button/delete-webp.php`:
- Update button label from `delete webp images` to `delete next-gen images`

### Estimate the effort ✅

### PR DESCRIPTION
**Pull request by Miraeld**
## Description

Some labels get changed from mentioning `WebP` to `Next-gen images`

Fixes #763 

## Type of change

- Bug fix (non-breaking change which fixes an issue).

## Is the solution different from the one proposed during the grooming?

No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

### CODE REVIEW

**Review by jeawhanlee — APPROVED** [review]

**Comment by jeawhanlee** [comment]
@MathieuLamiot @piotrbak Does this need QA?

**Comment by MathieuLamiot** [comment]
I don't think so

**Comment by jeawhanlee** [comment]
Thanks @MathieuLamiot 
We can merge this @Miraeld

**Comment by MathieuLamiot** [comment]
@Miraeld Since this is related to a major release, I would recommend not merging into develop but a dedicated major branch. Otherwise, it would be included in the next minor version if any ; would that be OK @piotrbak ?

(cc @Tabrisrp )

**Comment by piotrbak** [comment]
@MathieuLamiot Yes, we should have a separate branch for the major.

**Pull request merged**
